# Generated by Django 5.2.4 on 2025-07-30 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alias", models.CharField(max_length=100, verbose_name="별칭")),
                (
                    "hashed_mac_address",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="해싱된 MAC주소"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활동 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "Device",
                "verbose_name_plural": "Devices",
            },
        ),
        migrations.CreateModel(
            name="DeviceAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consecutive_count",
                    models.PositiveIntegerField(default=1, verbose_name="연속 개수"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="device.device",
                        verbose_name="디바이스",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Access Log",
                "verbose_name_plural": "Device Access Logs",
                "indexes": [
                    models.Index(
                        fields=["device", "-updated_at"],
                        name="device_updated_at_desc_idx",
                    )
                ],
            },
        ),
    ]
