# Generated by Django 5.2.4 on 2025-07-30 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_time",
                    models.DateTimeField(db_index=True, verbose_name="요청 시간"),
                ),
                (
                    "request_url",
                    models.CharField(max_length=255, verbose_name="요청 주소"),
                ),
                (
                    "is_success",
                    models.BooleanField(default=False, verbose_name="성공 여부"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="device.device",
                        verbose_name="디바이스",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
            },
        ),
    ]
